### ISSUE TITLE
Error when selecting model parameters in the model training toolbox

### ISSUE THREAD

**Issue by a-fakhri** [CivML-PolyMtl/OpenIPDM#4]
![image](https://github.com/CivML-PolyMtl/OpenIPDM/assets/65111198/dd1ee72a-0844-416e-99af-b100eb1b0274)
![image](https://github.com/CivML-PolyMtl/OpenIPDM/assets/65111198/ebab58e5-f5c2-4fe1-87f9-9153c62c506f)

**Comment by zachamida** [comment]
This only happens when a structural category is not selected, or have you noticed other instances where it happens?

**Comment by a-fakhri** [comment]
> This only happens when a structural category is not selected, or have you noticed other instances where it happens?

It happens even when a structural category is assigned to a model.

**Comment by zachamida** [comment]
issue is fixed
